### PR TITLE
Boost preflights code review

### PR DESCRIPTION
**Pull request by eparker12**
The branch adds booster dose comparisons according to primary series (AZ-AZ-BNT vs BNT-BNT-BNT) to the preflight checks and cox models. Follow-up for the booster dose is limited to a single 84-day period starting on the day of dose 3, so not stratified models are required.

I have also added a modification to the calendar-time models for both the primary and booster analyses with a single follow-up period. This is specified via the 'calendartimefull' argument. These models use the infrastructure of the stratified models to specify tstart and tstop but then retain a single comparison period in the final analysis - hopefully equivalent to the full person-time models.

Since the 'calendartimefull' models only have a single level for 'timesincevax_pw', the formula for these are modified as follows on line 587:

`if (timescale=="calendartimefull") {
formula0_strata <- as.formula(glue("Surv(tstart, tstop, ind_outcome) ~ {expo}"))
} else {
formula0_strata <- as.formula(glue("Surv(tstart, tstop, ind_outcome) ~ {expo}:strata({vars0})"))
}`

### CODE REVIEW

**Comment by elsie-h** [comment]
I'm wondering if it would be cleaner to implement the `"calendertimefull"` model in the same way that the the `"persontime"` full model is implemented (i.e. `timescale="calendartime"`, then create both `full` and `stratified` datasets). I'm happy to make the edits, but I wanted to check first that there wasn't a reason for not doing this!

**Comment by eparker12** [comment]
I agree this approach would be cleaner. My primary reason for the current approach was to borrow the coding infrastructure of the stratified analyses that sets up the calendar time-specific tstart and tstop variables.

But I'm happy to go with the simpler full/stratified approach if you are happy to suggest a way to do this.

**Comment by elsie-h** [comment]
Note that the edits that I reverted are now in a separate branch called [elsie-edits-20220711](https://github.com/opensafely/ckd-coverage-ve/tree/elsie-edits-20220711) so that it shows the diff relative to this branch, rather than relative to main (as was the case when I made the edits in this branch).

**Review by eparker12 — COMMENTED** [review]
Approve for merge to main branch

**Pull request merged**
